### ISSUE TITLE
As a team member, I want to understand the meta project management needs to I can balance my work accordingly. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/data-federation-report#29]
## User story
Figure out our meta project management approaches, kanban / task assignments, tracking, weekly reporting, etc. 
  
## Acceptance criteria
- [x] Set up tracking board
- [x] Articulate more detail around the final deliverables for this project
- [x] Timeline 
- [x] Build out the cards / user stories
- [x] Set up templates for weekly reports and retros
- [x] Make sure all aligns to how the team wants to work
